# Generated by Django 4.2.11 on 2024-05-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspetor',
            options={'ordering': ['-id'], 'verbose_name': 'Inpetor', 'verbose_name_plural': 'Inspetors'},
        ),
    ]
