# Generated by Django 4.2.11 on 2024-05-04 22:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_inspetor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('type_item', models.CharField(choices=[('LANCHA', 'LANCAHAR'), ('NAVIO', 'NAVIO'), ('IATE', 'IATE'), ('JET_SKI', 'JET_SKI'), ('VELEIRO', 'VELEIRO'), ('REBOQUE', 'REBOQUE')], max_length=100)),
                ('address', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_locate', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vistoria',
                'verbose_name_plural': 'Vistorias',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VistoriaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Images')),
                ('vistoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistoria_images', to='myapp.vistoria')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrarVistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_start', models.DateTimeField(verbose_name='Inicio')),
                ('dt_end', models.DateTimeField(verbose_name='Fim')),
                ('create_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('inspetor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.inspetor')),
                ('vistoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_location', to='myapp.vistoria')),
            ],
            options={
                'verbose_name': 'Registrar Vistoria',
                'verbose_name_plural': 'Registrar Vistorias',
                'ordering': ['-id'],
            },
        ),
    ]
