# Generated by Django 4.2.11 on 2024-05-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_vistoria_vistoriaimage_registrarvistoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspetor',
            options={'ordering': ['-id'], 'verbose_name': 'Inspetor', 'verbose_name_plural': 'Inspetores'},
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='type_item',
            field=models.CharField(choices=[('LANCHA', 'LANCHAR'), ('NAVIO', 'NAVIO'), ('IATE', 'IATE'), ('JET_SKI', 'JET_SKI'), ('VELEIRO', 'VELEIRO'), ('REBOQUE', 'REBOQUE')], max_length=100),
        ),
    ]
