# Generated by Django 4.2.11 on 2024-05-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_inspetor_options_alter_vistoria_type_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspetor',
            options={'ordering': ['-id'], 'verbose_name': 'Inspetor', 'verbose_name_plural': 'Inspetors'},
        ),
        migrations.RenameField(
            model_name='inspetor',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='inspetor',
            old_name='name',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='inspetor',
            old_name='phone',
            new_name='Telefone',
        ),
    ]
