# Generated by Django 4.2.11 on 2024-05-04 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_inspetor_options_rename_email_inspetor_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspetor',
            options={'ordering': ['-id'], 'verbose_name': 'Inspetor', 'verbose_name_plural': 'Inspetores'},
        ),
        migrations.RenameField(
            model_name='vistoria',
            old_name='code',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='vistoria',
            old_name='address',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='vistoria',
            old_name='is_locate',
            new_name='esta_locado',
        ),
        migrations.RenameField(
            model_name='vistoria',
            old_name='price',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='vistoria',
            old_name='type_item',
            new_name='tipo_item',
        ),
    ]
