# Generated by Django 4.2.11 on 2024-05-04 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_create_at_registrarvistoria_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrarvistoria',
            name='vistoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_vistoria', to='myapp.vistoria'),
        ),
    ]
