# Generated by Django 4.2.11 on 2024-05-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_registrarvistoria_vistoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspetor',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='inspetor',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='inspetor',
            old_name='Telefone',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='vistoria',
            name='endereco',
        ),
        migrations.AddField(
            model_name='vistoria',
            name='bairro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='cep',
            field=models.CharField(default='00000000', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='cidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='complemento',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='rua',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='tipo_item',
            field=models.CharField(choices=[('LANCHA', 'LANCHA'), ('NAVIO', 'NAVIO'), ('IATE', 'IATE'), ('JET_SKI', 'JET_SKI'), ('VELEIRO', 'VELEIRO'), ('REBOQUE', 'REBOQUE')], max_length=100),
        ),
    ]
