# Generated by Django 4.2.11 on 2024-05-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_email_inspetor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistoria',
            name='cep',
            field=models.CharField(default='00000-000', max_length=8, null=True),
        ),
    ]
