# Generated by Django 4.2.11 on 2024-05-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_vistoria_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistoria',
            name='cep',
            field=models.CharField(default='00000000', max_length=8, null=True),
        ),
    ]
