# Generated by Django 4.2.11 on 2024-05-05 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_vistoria_cep'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrarVistoria',
            new_name='RegistraVistoria',
        ),
    ]
