name: Django Tests and Linting

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Save test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-reports

  lint:
    name: Check Python code style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: |
          flake8 --config=.flake8 .
